### ISSUE TITLE
lfs server 已無法使用

### ISSUE THREAD

**Issue by leo424y** [twgo/pian7sik4_gi2liau7#12]
很不幸它也是lvm擴充這次災情的受害者

各位管理者大家好：

OpenStack 私有雲儲存設備服務已恢復正常運作，如連線異常，請重開VM。

幾點事項提醒私有雲使用者：
1.OpenStack 私有雲提供實驗性質之環境，提供自助化服務，依需求自建。
2.本次OpenStack異常係儲存設備網路過載(iSCSI storage)，造成服務中斷。
3.如您的虛擬機使用映像檔建置且使用雲硬碟做LVM擴充，可能已無法開機，資訊室建
議重建。
4.VMware私有雲提供服務性質之環境，無自助化服務，如您有服務及需相對穩定的環
境，請向資訊室申請。

使用者如有問題，請與我聯絡。

謝謝

**Comment by sih4sing5hong5** [comment]
重設定一台lfs了後，去gpu彼台
```
gpu@gpu:~/git/pian7sik4_gi2liau7$  git lfs push --all
```

**Comment by leo424y** [comment]
收到，果然還是老大有遠見！我再重設

**Comment by leo424y** [comment]
已修復並更新 語料 repo https://github.com/twgo/pian7sik4_gi2liau7/commit/f5c6e421b5a4863ab79973745d117c9134ad73db
