### ISSUE TITLE
換新lfs server需要重lfs push

### ISSUE THREAD

**Issue by leo424y** [twgo/pian7sik4_gi2liau7#8]
https://github.com/twgo/pian7sik4_gi2liau7/tree/new_server

假定master語料最齊，對它先開了一個branch 若lfs push clone 測試OK再merge

若 @sih4sing5hong5  local有語料的話請協助git lfs push

無的話請告知何branch最齊我可clone/push

主要是改了lfsconfig server 位置到
`"http://lfs:lfs@10.32.0.112:8080/repository/gitlfs-hosted/info/lfs"`

其它branch有需要也請merge，但請留意語料已push齊全

謝謝

**Comment by sih4sing5hong5** [comment]
master上新，有`noise.sound`
